---
title: "Activity 3"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
cancer <- tibble(case = factor(c(rep(1,3),rep(0,3)),
                               levels = c(0,1),
                               labels = c("control","case")),
                 x1 = c(1,2,3,4,2,3),
                 x2 = c(4,8,6,0,2,4))
cancer
```

```{r}
cancer %>% ggplot(aes(x1,x2)) + geom_point(aes(color=case))
```

# Question 1

```{r}
cancer_summary <- cancer %>%
  group_by(case) %>%
  summarise(x1=mean(x1), x2=mean(x2))

cancer_summary
```

```{r}
u1 <- cancer %>%
  filter(case=="case") %>%
  summarise(x1=mean(x1), x2=mean(x2))

u1 <- t(as.matrix(u1))
u1
```
```{r}
u2 <- cancer %>%
  filter(case=="control") %>%
  summarise(x1=mean(x1), x2=mean(x2))

u2 <- t(as.matrix(u2))
u2
```

# Question 2

```{r}
X <- matrix(c(-1,0,1,1,-1,0,-2,2,0,-2,0,2), nrow=6, byrow=FALSE)
X
```

```{r}
s <- 1/4 * t(X) %*% X
s
```
```{r}
si <- solve(s)
si
```

# Question 4

```{r}
a1 <-  si %*% u1
b1 <- t(u1) %*% si %*% u1

a2 <- si %*% u2
b2 <- t(u2) %*% si %*% u2

b1
```
# Question 5

```{r}
predict_cancer <- function(x) {
  x %*% (a1 - a2) + 1/2 * (b1 - b2)
}
```

```{r}
x1 <- 0
x2 <- -x1 + 1.5
predict_cancer(c(x1, x2))

x2 <- x1 + 11.5
predict_cancer(c(x1, x2))

x2 <- -x1 - 11.5
predict_cancer(c(x1, x2))

x2 <- x1 + 1.5
predict_cancer(c(x1, x2))
```


# Question 6

```{r}
predict_cancer(c(2,6))
```

